/* eslint-disable jsx-a11y/alt-text */
// pages/projects/[slug].tsx
import Link from 'next/link';
import { Image } from 'react-datocms';
import { GetStaticPaths } from 'next';
import { useRouter } from 'next/router';
import Head from 'next/head';
import { FaArrowRight, FaCalendar } from 'react-icons/fa';
import { DiCodeBadge } from 'react-icons/di';
import datoCmsClient from '../../dato-cms';

import Layout from '../../src/components/Layout';
import H1 from '../../src/components/UI/Typography/H1';
import P from '../../src/components/UI/Typography/Paragraph';
import { datoCmsQuery } from '../../src/querys/datoCmsQuery';
import { SingleProject } from '../../styles/sharedstyled';
import Button from '../../src/components/UI/Typography/Button';
import { RevealWrapper } from 'next-reveal';

// interface ProjectPageProps {
//     project: {
//       name: string,
//       description: string,
//       link: string,
//       tech: string,
//       coverImage: {
//         responsiveImage: string
//       },
//       date: string,
//     };
// }

export default function ProjectPage({ project }: any) {
    console.log('project in project page', project);
    const router = useRouter();

    if (router.isFallback) {
      return <div>Loading...</div>;
    }
  
    if (!project) {
      // Handle the case when project is undefined
      return <div>Project not found</div>;
    }

  return (
    <>
    <Head>
      <title>About | Aimee Tacchi Portfolio 2023</title>
      <meta name="description" content="Aimee Tacchi Portfolio 2023 Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <Layout>
      <SingleProject>
        <RevealWrapper origin='bottom' delay={250} duration={1500} distance='800px' viewOffset={{top:  25,  right:0,  bottom:  10,  left:25}}>
          <H1 className="mt-10">{project.name}</H1>
        </RevealWrapper>

        <RevealWrapper origin='bottom' delay={250} duration={1500} distance='800px' viewOffset={{top:  25,  right:0,  bottom:  10,  left:25}}>
          <P className="mt-5 flex items-center gap-2">
            <FaCalendar className="inline-block"/> Created: {project.date}
          </P>
          <P className="mt-5">{project.description}</P>
        </RevealWrapper>
        <RevealWrapper origin='bottom' delay={250} duration={1500} distance='800px' viewOffset={{top:  25,  right:0,  bottom:  10,  left:25}}>
          <ul>
              <li className="my-5 flex lg:items-center gap-2">
                <DiCodeBadge className="w-20 lg:w-10 h-8"/> Tech: {project.tech}
              </li>
          </ul>
        </RevealWrapper>
        <div className="lg:flex gap-5">
          {project.gallery.map((image: any) => (
              <Image
                key={image.id}
                data={
                  image.responsiveImage
                }
                className="w-full h-full"/>  
          ))}
        </div>

        <a  
          href={project.link}
          target="_blank"
          rel="noreferrer"
          className="flex no-underline justify-center items-center gap-2 my-5 font-bold underline"
            >
              <Button>
                View Project <FaArrowRight />
              </Button>
        </a>

       </SingleProject>
    </Layout>
    </>
  );
};

export const getStaticPaths: GetStaticPaths = async () => {
    const projects = await datoCmsClient.request(datoCmsQuery);
   
    const paths = projects.allProjects.map((project: any) => ({
      params: { slug: project.slug.toString() },
    }));

    return {
      paths,
      fallback: true,
      
    };
};

export async function getStaticProps({ params }: any) {
    
    console.log('params', params)
    const projects = await datoCmsClient.request(datoCmsQuery);

    const project = projects.allProjects.find(
        (project: any) => project.slug === params?.slug
    );

   console.log('project in get staticProps', project);

  return {
    props: {
      project:  project || null,
    },
  };
};

