// pages/projects/[slug].tsx
import Link from 'next/link';
import { GetStaticPaths } from 'next';
import { useRouter } from 'next/router';
import Head from 'next/head';
import { FaArrowRight, FaCalendar } from 'react-icons/fa';
import { DiCodeBadge } from 'react-icons/di';
import datoCmsClient from '../../dato-cms';

import Layout from '../../src/components/Layout';
import H1 from '../../src/components/UI/Typography/H1';
import P from '../../src/components/UI/Typography/Paragraph';
import { datoCmsQuery } from '../../src/querys/datoCmsQuery';
import { Image } from 'react-datocms';
import { SingleProject } from '../../styles/sharedstyled';

// interface ProjectPageProps {
//     project: {
//       name: string,
//       description: string,
//       link: string,
//       tech: string,
//       coverImage: {
//         responsiveImage: string
//       },
//       date: string,
//     };
// }

export default function ProjectPage({ project }: any) {
    console.log('project in project page', project);
    const router = useRouter();

    if (router.isFallback) {
      return <div>Loading...</div>;
    }
  
    if (!project) {
      // Handle the case when project is undefined
      return <div>Project not found</div>;
    }

  return (
    <>
    <Head>
      <title>About | Aimee Tacchi Portfolio 2023</title>
      <meta name="description" content="Aimee Tacchi Portfolio 2023 Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <Layout>
       <SingleProject className="m-10">
         
         <H1>{project.name}</H1>
         <P>{project.description}</P>

          <ul className="details">
              <li className="date"><FaCalendar className="inline-block"/> Created: {project.date}</li>
              <li className="tags">
                  <ul>
                      <li><DiCodeBadge className="inline-block"/> Tech: {project.tech}</li>
                  </ul>
              </li>   
          </ul>

          <Link
              className="font-bold underline"
              href={project.link}>
                  View Project <FaArrowRight />
          </Link>

       </SingleProject>
    </Layout>
    </>
  );
};

export const getStaticPaths: GetStaticPaths = async () => {
    const projects = await datoCmsClient.request(datoCmsQuery);
   
    const paths = projects.allProjects.map((project: any) => ({
      params: { slug: project.slug.toString() },
    }));

    return {
      paths,
      fallback: true,
      
    };
};

export async function getStaticProps({ params }: any) {
    
    console.log('params', params)
    const projects = await datoCmsClient.request(datoCmsQuery);

    const project = projects.allProjects.find(
        (project: any) => project.slug === params?.slug
    );

   console.log('project in get staticProps', project);

  return {
    props: {
      project:  project || null,
    },
  };
};

