import Head from 'next/head'
import Layout from '../src/components/Layout';
import About from '../src/components/About';

export default function AboutPage() {

  return (
    <>
      <Head>
        <title>About | Aimee Tacchi Portfolio 2023</title>
        <meta name="description" content="Aimee Tacchi Portfolio 2023 Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <About/>
      </Layout>
    </>
  )
}



